require("settings")
require("keymaps")
require("config.lazy")

require("config.alpha")
require("config.bufferline")
require("config.lualine")
require("config.luasnip")
require("config.markdown")
require("config.noice")
require("config.nvim-colorizer")
require("config.nvim-notify")
require("config.nvim-ts-autotag")
require("config.oil")
require("config.telescope")
require("config.toggleterm")
require("config.which-key")
