#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-5 -d I II III IV
bspc monitor DP-3 -d q e

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color '#61afef'
bspc config focused_border_color '#e06c75'
bspc config active_border_color '#61afef'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^5' follow=on focus=on
bspc rule -a discord desktop='^5'
bspc rule -a Mailspring state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/autostart.sh
