#! /bin/sh

######################################################
#  ██████╗░░██████╗██████╗░░██╗░░░░░░░██╗███╗░░░███╗ #
#  ██╔══██╗██╔════╝██╔══██╗░██║░░██╗░░██║████╗░████║ #
#  ██████╦╝╚█████╗░██████╔╝░╚██╗████╗██╔╝██╔████╔██║ #
#  ██╔══██╗░╚═══██╗██╔═══╝░░░████╔═████║░██║╚██╔╝██║ #
#  ██████╦╝██████╔╝██║░░░░░░░╚██╔╝░╚██╔╝░██║░╚═╝░██║ #
#  ╚═════╝░╚═════╝░╚═╝░░░░░░░░╚═╝░░░╚═╝░░╚═╝░░░░░╚═╝ #     
######################################################

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-3 -d 1 2 3 4 
bspc monitor DP-1 -d z x c

bspc config border_width         1
bspc config window_gap           8

# blue and black
bspc config focused_border_color '#82aaff'
bspc config active_border_color '#828bb8'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^5'
bspc rule -a Mailspring state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/autostart.sh
